[default]
BROKER = "redis://localhost:6379/0"
DB = "/home/shaktsin/projects/demo/controlplane/md.db"
DP_INGRESS_EP = "http://k8s-default-hellokub-b2291d6458-1199849968.us-east-2.elb.amazonaws.com"
debug = false
log_level = "INFO"
